services:
  - type: web
    name: optidem
    repo: https://github.com/weichencsu/gohugo_optidem
    runtime: static
    buildCommand: chmod a+x build.sh && ./build.sh
    staticPublishPath: public
    envVars:
      - key: DART_SASS_VERSION
        value: 1.97.3
      - key: GO_VERSION
        value: 1.26.0
      - key: HUGO_VERSION
        value: 0.156.0
      - key: NODE_VERSION
        value: 24.13.1
      - key: TZ
        value: Europe/Oslo